declare module 'redux-logger'
declare module 'lodash'
declare module 'pdf-viewer-reactjs'
declare module 'react-file-viewer'
declare module 'uuid'
// declare module 'dom-to-image'
declare module 'dom-to-image'
declare module 'marked'
declare module 'html-to-docx'
declare module 'file-saver'
declare module 'crypto-js'
declare module 'react-syntax-highlighter'
